"""Free lightweight theme packs for JARVIS UI."""
from __future__ import annotations

from typing import Any


THEMES: dict[str, dict[str, Any]] = {
    "midnight_hud": {
        "label": "Midnight HUD",
        "bg": "#05080f",
        "panel": "#0a1220",
        "sidebar": "#071018",
        "accent": "#5ce1ff",
        "accent2": "#9ef01a",
        "text": "#d7e6f5",
        "muted": "#6a7a8a",
        "button": "#0b3d5c",
        "danger": "#3a1a1a",
        "chat_bg": "#0a1220",
        "entry_bg": "#0d1520",
        "avatar": "orb",
        "effect": "hud",
    },
    "ember_core": {
        "label": "Ember Core",
        "bg": "#120808",
        "panel": "#1a0e0e",
        "sidebar": "#140a0a",
        "accent": "#ff6b4a",
        "accent2": "#ffd166",
        "text": "#f5e6e0",
        "muted": "#8a6a6a",
        "button": "#5c1b0b",
        "danger": "#3a1010",
        "chat_bg": "#1a0e0e",
        "entry_bg": "#221212",
        "avatar": "robot",
        "effect": "heartbeat",
    },
    "forest_soft": {
        "label": "Forest Soft",
        "bg": "#07140f",
        "panel": "#0c1c16",
        "sidebar": "#091510",
        "accent": "#5ddea0",
        "accent2": "#c8facc",
        "text": "#e0f5ea",
        "muted": "#6a8a7a",
        "button": "#0b3d2c",
        "danger": "#1a2a1a",
        "chat_bg": "#0c1c16",
        "entry_bg": "#10241c",
        "avatar": "orb",
        "effect": "waveform",
    },
    "arctic_glass": {
        "label": "Arctic Glass",
        "bg": "#0a1018",
        "panel": "#121a26",
        "sidebar": "#0e1520",
        "accent": "#a8c7ff",
        "accent2": "#e8f0ff",
        "text": "#e8eef8",
        "muted": "#7a8aa0",
        "button": "#243a5c",
        "danger": "#1a2030",
        "chat_bg": "#121a26",
        "entry_bg": "#182232",
        "avatar": "orb",
        "effect": "hud",
    },
    "neon_play": {
        "label": "Neon Play",
        "bg": "#0b0614",
        "panel": "#140a22",
        "sidebar": "#10081c",
        "accent": "#d946ef",
        "accent2": "#22d3ee",
        "text": "#f5e8ff",
        "muted": "#8a7a9a",
        "button": "#4a0b5c",
        "danger": "#2a1030",
        "chat_bg": "#140a22",
        "entry_bg": "#1c1030",
        "avatar": "robot",
        "effect": "waveform",
    },
    # Phase 2 original themes
    "armor_ai": {
        "label": "Armor AI (futuristic armored)",
        "bg": "#0a0c10",
        "panel": "#141820",
        "sidebar": "#0e1218",
        "accent": "#c0c8d4",
        "accent2": "#5ce1ff",
        "text": "#e8ecf2",
        "muted": "#7a8494",
        "button": "#2a3344",
        "danger": "#3a2020",
        "chat_bg": "#12161e",
        "entry_bg": "#1a2030",
        "avatar": "hud",
        "effect": "hud",
    },
    "green_power": {
        "label": "Green Power",
        "bg": "#04140a",
        "panel": "#0a1f12",
        "sidebar": "#06180e",
        "accent": "#39ff14",
        "accent2": "#a8ff60",
        "text": "#e6ffe6",
        "muted": "#5a8a5a",
        "button": "#0d3d1a",
        "danger": "#1a2a1a",
        "chat_bg": "#0a1f12",
        "entry_bg": "#0f2a18",
        "avatar": "orb",
        "effect": "heartbeat",
    },
    "shield_hero": {
        "label": "Shield Hero",
        "bg": "#0a1020",
        "panel": "#122040",
        "sidebar": "#0c1830",
        "accent": "#4da3ff",
        "accent2": "#ff4d4d",
        "text": "#e8f0ff",
        "muted": "#6a7a9a",
        "button": "#1a3a6a",
        "danger": "#3a1a1a",
        "chat_bg": "#122040",
        "entry_bg": "#183050",
        "avatar": "orb",
        "effect": "hud",
    },
    "cosmic_energy": {
        "label": "Cosmic Energy",
        "bg": "#0a0618",
        "panel": "#160e2e",
        "sidebar": "#100a22",
        "accent": "#b388ff",
        "accent2": "#ff80ab",
        "text": "#f3e5ff",
        "muted": "#8a7aaa",
        "button": "#3d1a6a",
        "danger": "#2a1030",
        "chat_bg": "#160e2e",
        "entry_bg": "#1e1440",
        "avatar": "orb",
        "effect": "waveform",
    },
    "speed_tech": {
        "label": "Speed Tech",
        "bg": "#0c0c0c",
        "panel": "#161616",
        "sidebar": "#101010",
        "accent": "#ff9100",
        "accent2": "#00e5ff",
        "text": "#f5f5f5",
        "muted": "#888888",
        "button": "#3d2800",
        "danger": "#3a1010",
        "chat_bg": "#161616",
        "entry_bg": "#1e1e1e",
        "avatar": "robot",
        "effect": "waveform",
    },
    "light_mode": {
        "label": "Light Mode",
        "bg": "#f4f6fa",
        "panel": "#ffffff",
        "sidebar": "#e8ecf4",
        "accent": "#1565c0",
        "accent2": "#2e7d32",
        "text": "#1a1a1a",
        "muted": "#667788",
        "button": "#1565c0",
        "danger": "#c62828",
        "chat_bg": "#ffffff",
        "entry_bg": "#eef2f8",
        "avatar": "orb",
        "effect": "minimal",
    },
}


def get_theme(name: str) -> dict[str, Any]:
    return dict(THEMES.get(name) or THEMES["midnight_hud"])


def list_themes() -> str:
    return "Themes: " + ", ".join(f"{k} ({v['label']})" for k, v in THEMES.items())
